/**
 * Seeds the DB with real Mumbai sample listings so the UI is immediately testable.
 * Run: npm run seed
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { upsertListings } from "../lib/supabase";

const LISTINGS = [
  // ── Bandra West ──────────────────────────────────────────────
  {
    source: "magicbricks" as const,
    source_id: "mb-bkc-001",
    url: "https://www.magicbricks.com/flats-for-rent-in-bandra-west-mumbai/residential-rent_8",
    title: "2 BHK Flat in Bandra West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 85000,
    price_unit: "per_month" as const,
    area_sqft: 950,
    bhk: 2,
    furnishing: "furnished" as const,
    floor: 8,
    total_floors: 14,
    locality: "Bandra West",
    city: "Mumbai",
    lat: 19.0596,
    lng: 72.8295,
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600"],
    floor_plan_images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400"],
    amenities: ["Gym", "Swimming Pool", "Security", "Parking", "Lift"],
    description: "Spacious 2 BHK in prime Bandra West location. Walking distance to Linking Road and Carter Road. Sea view from upper floors.",
    broker_name: "Rajan Properties",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
  {
    source: "housing" as const,
    source_id: "hs-bandra-002",
    url: "https://housing.com/in/buy/flats-apartments-in-bandra-west/mumbai",
    title: "3 BHK Sea View Apartment in Bandra West",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 45000000,
    price_unit: "total" as const,
    area_sqft: 1600,
    bhk: 3,
    furnishing: "semi-furnished" as const,
    floor: 12,
    total_floors: 20,
    locality: "Bandra West",
    city: "Mumbai",
    lat: 19.0612,
    lng: 72.8261,
    images: ["https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=600"],
    floor_plan_images: [],
    amenities: ["Sea View", "Gym", "Clubhouse", "24hr Security", "Power Backup"],
    description: "Luxurious 3 BHK with partial sea view in Bandra West. Premium society with world-class amenities.",
    broker_name: "Premium Homes",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Andheri West ─────────────────────────────────────────────
  {
    source: "99acres" as const,
    source_id: "99-andheri-001",
    url: "https://www.99acres.com/search/property/rent/andheri-west-mumbai?city=11&preference=S&area_unit=1&res_com=R",
    title: "1 BHK Flat in Andheri West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 32000,
    price_unit: "per_month" as const,
    area_sqft: 550,
    bhk: 1,
    furnishing: "semi-furnished" as const,
    floor: 3,
    total_floors: 7,
    locality: "Andheri West",
    city: "Mumbai",
    lat: 19.1362,
    lng: 72.8296,
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600"],
    floor_plan_images: [],
    amenities: ["Parking", "Lift", "Security"],
    description: "Well-maintained 1 BHK near Andheri station. Close to metro, malls and offices.",
    broker_name: "City Spaces",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
  {
    source: "nobroker" as const,
    source_id: "nb-andheri-002",
    url: "https://www.nobroker.in/property/rent/flat-in-andheri-west-mumbai/",
    title: "2 BHK Flat in Andheri West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 52000,
    price_unit: "per_month" as const,
    area_sqft: 850,
    bhk: 2,
    furnishing: "unfurnished" as const,
    floor: 5,
    total_floors: 10,
    locality: "Andheri West",
    city: "Mumbai",
    lat: 19.1308,
    lng: 72.8218,
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Parking", "Lift"],
    description: "Direct owner. No brokerage. 2 BHK in gated society near Versova metro.",
    broker_name: "Owner",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Powai ─────────────────────────────────────────────────────
  {
    source: "magicbricks" as const,
    source_id: "mb-powai-001",
    url: "https://www.magicbricks.com/flats-for-rent-in-powai-mumbai/residential-rent_8",
    title: "2 BHK Lake View Flat in Powai",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 65000,
    price_unit: "per_month" as const,
    area_sqft: 1100,
    bhk: 2,
    furnishing: "furnished" as const,
    floor: 15,
    total_floors: 25,
    locality: "Powai",
    city: "Mumbai",
    lat: 19.1176,
    lng: 72.9060,
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600"],
    floor_plan_images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400"],
    amenities: ["Lake View", "Swimming Pool", "Gym", "Clubhouse", "Valet Parking"],
    description: "Fully furnished lake-facing 2 BHK in Hiranandani Gardens. Top floor with panoramic view.",
    broker_name: "Hiranandani Realty",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
  {
    source: "housing" as const,
    source_id: "hs-powai-002",
    url: "https://housing.com/in/buy/flats-apartments-in-powai/mumbai",
    title: "3 BHK in Powai Hiranandani",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 32000000,
    price_unit: "total" as const,
    area_sqft: 1450,
    bhk: 3,
    furnishing: "semi-furnished" as const,
    floor: 10,
    total_floors: 22,
    locality: "Powai",
    city: "Mumbai",
    lat: 19.1193,
    lng: 72.9082,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Pool", "Jogging Track", "Multiplex nearby", "School nearby"],
    description: "Premium 3 BHK in Hiranandani Estate. Gated community with excellent connectivity to BKC and Andheri.",
    broker_name: "PropVista",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Worli ──────────────────────────────────────────────────────
  {
    source: "99acres" as const,
    source_id: "99-worli-001",
    url: "https://www.99acres.com/search/property/buy/worli-mumbai?city=11&preference=S&area_unit=1&res_com=R",
    title: "4 BHK Luxury Flat in Worli Sea Face",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 120000000,
    price_unit: "total" as const,
    area_sqft: 3200,
    bhk: 4,
    furnishing: "furnished" as const,
    floor: 28,
    total_floors: 35,
    locality: "Worli",
    city: "Mumbai",
    lat: 19.0114,
    lng: 72.8152,
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600"],
    floor_plan_images: [],
    amenities: ["Sea View", "Helipad", "Concierge", "Private Pool", "Smart Home"],
    description: "Ultra-luxury 4 BHK on Worli Sea Face. Unobstructed Arabian Sea views. Private lift lobby.",
    broker_name: "Elite Properties",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Goregaon East ─────────────────────────────────────────────
  {
    source: "nobroker" as const,
    source_id: "nb-goregaon-001",
    url: "https://www.nobroker.in/property/rent/flat-in-goregaon-east-mumbai/",
    title: "2 BHK Flat in Goregaon East",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 38000,
    price_unit: "per_month" as const,
    area_sqft: 780,
    bhk: 2,
    furnishing: "semi-furnished" as const,
    floor: 6,
    total_floors: 12,
    locality: "Goregaon East",
    city: "Mumbai",
    lat: 19.1663,
    lng: 72.8526,
    images: ["https://images.unsplash.com/photo-1615873968403-89e068629265?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Children Play Area", "Parking", "Security"],
    description: "No brokerage. Owner-listed 2 BHK in gated society near Oberoi Mall and Goregaon station.",
    broker_name: "Owner",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Malad West ────────────────────────────────────────────────
  {
    source: "magicbricks" as const,
    source_id: "mb-malad-001",
    url: "https://www.magicbricks.com/flats-for-rent-in-malad-west-mumbai/residential-rent_8",
    title: "1 BHK Flat in Malad West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 24000,
    price_unit: "per_month" as const,
    area_sqft: 480,
    bhk: 1,
    furnishing: "unfurnished" as const,
    floor: 2,
    total_floors: 6,
    locality: "Malad West",
    city: "Mumbai",
    lat: 19.1876,
    lng: 72.8481,
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600"],
    floor_plan_images: [],
    amenities: ["Parking", "Security"],
    description: "Affordable 1 BHK near Malad station. 5 min walk to Inorbit Mall.",
    broker_name: "Malad Properties",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Chembur ───────────────────────────────────────────────────
  {
    source: "housing" as const,
    source_id: "hs-chembur-001",
    url: "https://housing.com/in/buy/flats-apartments-in-chembur/mumbai",
    title: "2 BHK Flat in Chembur",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 12500000,
    price_unit: "total" as const,
    area_sqft: 950,
    bhk: 2,
    furnishing: "unfurnished" as const,
    floor: 4,
    total_floors: 9,
    locality: "Chembur",
    city: "Mumbai",
    lat: 19.0622,
    lng: 72.9005,
    images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Parking", "Children Play Area"],
    description: "Ready possession 2 BHK in Chembur. Well-connected via Eastern Express Highway and Monorail.",
    broker_name: "Chembur Homes",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Dadar ─────────────────────────────────────────────────────
  {
    source: "99acres" as const,
    source_id: "99-dadar-001",
    url: "https://www.99acres.com/search/property/rent/dadar-west-mumbai?city=11&preference=S&area_unit=1&res_com=R",
    title: "2 BHK in Dadar West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 55000,
    price_unit: "per_month" as const,
    area_sqft: 820,
    bhk: 2,
    furnishing: "furnished" as const,
    floor: 7,
    total_floors: 11,
    locality: "Dadar West",
    city: "Mumbai",
    lat: 19.0186,
    lng: 72.8438,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Lift", "Security", "Parking"],
    description: "Centrally located 2 BHK in Dadar West. Walking distance to Shivaji Park and Dadar station.",
    broker_name: "Central Mumbai Realty",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── BKC ───────────────────────────────────────────────────────
  {
    source: "nobroker" as const,
    source_id: "nb-bkc-001",
    url: "https://www.nobroker.in/property/rent/flat-in-bandra-kurla-complex-mumbai/",
    title: "3 BHK in BKC — Corporate Housing",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 140000,
    price_unit: "per_month" as const,
    area_sqft: 1800,
    bhk: 3,
    furnishing: "furnished" as const,
    floor: 20,
    total_floors: 30,
    locality: "Bandra Kurla Complex",
    city: "Mumbai",
    lat: 19.0657,
    lng: 72.8677,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600"],
    floor_plan_images: [],
    amenities: ["Business Centre", "Gym", "Concierge", "Pool", "Valet"],
    description: "Premium corporate housing 3 BHK 2 min walk from BKC offices. Ideal for expats and senior executives.",
    broker_name: "Owner",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Lower Parel ───────────────────────────────────────────────
  {
    source: "magicbricks" as const,
    source_id: "mb-lowerparel-001",
    url: "https://www.magicbricks.com/flats-for-rent-in-lower-parel-mumbai/residential-rent_8",
    title: "2 BHK in Lower Parel — High Rise",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 95000,
    price_unit: "per_month" as const,
    area_sqft: 1050,
    bhk: 2,
    furnishing: "furnished" as const,
    floor: 22,
    total_floors: 35,
    locality: "Lower Parel",
    city: "Mumbai",
    lat: 18.9976,
    lng: 72.8302,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
      "https://images.unsplash.com/photo-1574691250077-03a929faece5?w=600",
    ],
    amenities: ["Infinity Pool", "Gym", "Concierge", "Sky Lounge", "Parking"],
    description: "Stunning high-rise 2 BHK with city skyline views. Steps from Phoenix Mills and Lower Parel station.",
    broker_name: "Parel Realty",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
  {
    source: "99acres" as const,
    source_id: "99-lowerparel-002",
    url: "https://www.99acres.com/search/property/buy/lower-parel-mumbai?city=11&preference=S&area_unit=1&res_com=R",
    title: "3 BHK Luxury in One Indiabulls — Lower Parel",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 65000000,
    price_unit: "total" as const,
    area_sqft: 1800,
    bhk: 3,
    furnishing: "semi-furnished" as const,
    floor: 30,
    total_floors: 40,
    locality: "Lower Parel",
    city: "Mumbai",
    lat: 18.9960,
    lng: 72.8318,
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    ],
    amenities: ["2 Pools", "Gym", "Squash Court", "Theatre", "Helipad"],
    description: "Premium 3 BHK in One Indiabulls. Mill-converted luxury complex in the heart of Mumbai's new CBD.",
    broker_name: "Ultra Luxury Homes",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Santacruz East ────────────────────────────────────────────
  {
    source: "nobroker" as const,
    source_id: "nb-santacruz-001",
    url: "https://www.nobroker.in/property/rent/flat-in-santacruz-east-mumbai/",
    title: "2 BHK Flat in Santacruz East",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 42000,
    price_unit: "per_month" as const,
    area_sqft: 780,
    bhk: 2,
    furnishing: "semi-furnished" as const,
    floor: 4,
    total_floors: 8,
    locality: "Santacruz East",
    city: "Mumbai",
    lat: 19.0794,
    lng: 72.8479,
    images: ["https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=600"],
    floor_plan_images: [],
    amenities: ["Parking", "Security", "Lift"],
    description: "No brokerage. Direct owner. 2 BHK near Santacruz station. Easy access to Bandra-Kurla Complex.",
    broker_name: "Owner",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Juhu ──────────────────────────────────────────────────────
  {
    source: "housing" as const,
    source_id: "hs-juhu-001",
    url: "https://housing.com/in/rent/flats-apartments-in-juhu/mumbai",
    title: "3 BHK Sea-Facing Flat in Juhu",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 175000,
    price_unit: "per_month" as const,
    area_sqft: 2100,
    bhk: 3,
    furnishing: "furnished" as const,
    floor: 9,
    total_floors: 12,
    locality: "Juhu",
    city: "Mumbai",
    lat: 19.1075,
    lng: 72.8263,
    images: ["https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    ],
    amenities: ["Sea View", "Private Terrace", "Gym", "Pool", "Staff Quarters"],
    description: "Premium sea-facing 3 BHK on Juhu Tara Road. Walking distance to Juhu Beach. Bollywood neighbourhood.",
    broker_name: "Juhu Estates",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
  {
    source: "magicbricks" as const,
    source_id: "mb-juhu-002",
    url: "https://www.magicbricks.com/flats-for-sale-in-juhu-mumbai/residential-sale_8",
    title: "4 BHK Bungalow in Juhu",
    listing_type: "buy" as const,
    property_type: "house" as const,
    price: 250000000,
    price_unit: "total" as const,
    area_sqft: 5000,
    bhk: 4,
    furnishing: "furnished" as const,
    floor: 0,
    total_floors: 2,
    locality: "Juhu",
    city: "Mumbai",
    lat: 19.1089,
    lng: 72.8277,
    images: ["https://images.unsplash.com/photo-1613977257363-707ba9348227?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
      "https://images.unsplash.com/photo-1574691250077-03a929faece5?w=600",
    ],
    amenities: ["Private Pool", "Garden", "Home Theatre", "Gym", "4 Parking"],
    description: "Iconic standalone bungalow in Juhu. 5000 sqft of prime real estate in Mumbai's most prestigious locality.",
    broker_name: "Celebrity Homes",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Vikhroli ──────────────────────────────────────────────────
  {
    source: "99acres" as const,
    source_id: "99-vikhroli-001",
    url: "https://www.99acres.com/search/property/rent/vikhroli-east-mumbai?city=11&preference=S&area_unit=1&res_com=R",
    title: "1 BHK in Vikhroli East",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 22000,
    price_unit: "per_month" as const,
    area_sqft: 450,
    bhk: 1,
    furnishing: "unfurnished" as const,
    floor: 2,
    total_floors: 5,
    locality: "Vikhroli East",
    city: "Mumbai",
    lat: 19.1006,
    lng: 72.9231,
    images: ["https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600"],
    floor_plan_images: [],
    amenities: ["Parking", "Security"],
    description: "Affordable 1 BHK near Vikhroli station. Close to Godrej One and JVLR.",
    broker_name: "Vikhroli Properties",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Thane ─────────────────────────────────────────────────────
  {
    source: "nobroker" as const,
    source_id: "nb-thane-001",
    url: "https://www.nobroker.in/property/sale/flat-in-thane-west-thane/",
    title: "3 BHK in Thane West — Lake View",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 18500000,
    price_unit: "total" as const,
    area_sqft: 1350,
    bhk: 3,
    furnishing: "semi-furnished" as const,
    floor: 12,
    total_floors: 20,
    locality: "Thane West",
    city: "Mumbai",
    lat: 19.2183,
    lng: 72.9781,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    ],
    amenities: ["Lake View", "Gym", "Pool", "Clubhouse", "Kids Zone"],
    description: "No brokerage. Spacious 3 BHK with Masunda Lake view in Thane West. Gated society, excellent schools nearby.",
    broker_name: "Owner",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
  {
    source: "housing" as const,
    source_id: "hs-thane-002",
    url: "https://housing.com/in/rent/flats-apartments-in-thane-west/thane",
    title: "2 BHK in Thane West — New Project",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 28000,
    price_unit: "per_month" as const,
    area_sqft: 850,
    bhk: 2,
    furnishing: "unfurnished" as const,
    floor: 6,
    total_floors: 14,
    locality: "Thane West",
    city: "Mumbai",
    lat: 19.2320,
    lng: 72.9854,
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Jogging Track", "Parking", "CCTV"],
    description: "New construction 2 BHK in Thane West. Metro connectivity coming soon. Good for families.",
    broker_name: "Thane Homes",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Navi Mumbai ───────────────────────────────────────────────
  {
    source: "magicbricks" as const,
    source_id: "mb-navimumbai-001",
    url: "https://www.magicbricks.com/flats-for-sale-in-kharghar-navi-mumbai/residential-sale_8",
    title: "3 BHK in Kharghar — Navi Mumbai",
    listing_type: "buy" as const,
    property_type: "flat" as const,
    price: 12000000,
    price_unit: "total" as const,
    area_sqft: 1250,
    bhk: 3,
    furnishing: "unfurnished" as const,
    floor: 8,
    total_floors: 15,
    locality: "Kharghar",
    city: "Mumbai",
    lat: 19.0474,
    lng: 73.0659,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    ],
    amenities: ["Gym", "Pool", "Club House", "Landscaped Garden", "Amphitheatre"],
    description: "Spacious 3 BHK in Kharghar. Navi Mumbai's fastest growing node. Central Park facing. Metro station 1km.",
    broker_name: "Navi Mumbai Realty",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Mulund ────────────────────────────────────────────────────
  {
    source: "99acres" as const,
    source_id: "99-mulund-001",
    url: "https://www.99acres.com/search/property/rent/mulund-west-mumbai?city=11&preference=S&area_unit=1&res_com=R",
    title: "2 BHK in Mulund West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 32000,
    price_unit: "per_month" as const,
    area_sqft: 760,
    bhk: 2,
    furnishing: "semi-furnished" as const,
    floor: 5,
    total_floors: 10,
    locality: "Mulund West",
    city: "Mumbai",
    lat: 19.1726,
    lng: 72.9559,
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600"],
    floor_plan_images: [],
    amenities: ["Gym", "Parking", "Security"],
    description: "Well-maintained 2 BHK in Mulund West. Quiet locality, good schools, close to Eastern Express Highway.",
    broker_name: "Mulund Properties",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Marine Lines ──────────────────────────────────────────────
  {
    source: "housing" as const,
    source_id: "hs-marinelines-001",
    url: "https://housing.com/in/rent/flats-apartments-in-marine-lines/mumbai",
    title: "2 BHK Sea-Facing in Marine Lines",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 120000,
    price_unit: "per_month" as const,
    area_sqft: 1000,
    bhk: 2,
    furnishing: "furnished" as const,
    floor: 7,
    total_floors: 10,
    locality: "Marine Lines",
    city: "Mumbai",
    lat: 18.9438,
    lng: 72.8230,
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600"],
    floor_plan_images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    ],
    amenities: ["Sea View", "Lift", "Security", "Parking"],
    description: "Charming 2 BHK on Marine Drive. Unbeatable Queen's Necklace view. Walk to Churchgate station.",
    broker_name: "South Mumbai Homes",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },

  // ── Kurla ─────────────────────────────────────────────────────
  {
    source: "nobroker" as const,
    source_id: "nb-kurla-001",
    url: "https://www.nobroker.in/property/rent/flat-in-kurla-west-mumbai/",
    title: "1 BHK in Kurla West",
    listing_type: "rent" as const,
    property_type: "flat" as const,
    price: 18000,
    price_unit: "per_month" as const,
    area_sqft: 420,
    bhk: 1,
    furnishing: "unfurnished" as const,
    floor: 1,
    total_floors: 4,
    locality: "Kurla West",
    city: "Mumbai",
    lat: 19.0726,
    lng: 72.8796,
    images: ["https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600"],
    floor_plan_images: [],
    amenities: ["Parking"],
    description: "No brokerage. Budget 1 BHK in Kurla West. Close to BKC, Kurla station and LBS Marg.",
    broker_name: "Owner",
    location_exact: false,
    scraped_at: new Date().toISOString(),
  },
];

async function seed() {
  console.log(`\n🌱 Seeding ${LISTINGS.length} Mumbai listings…\n`);
  try {
    await upsertListings(LISTINGS);
    console.log(`✅ Seeded ${LISTINGS.length} listings successfully`);
  } catch (err) {
    console.error("❌ Seed failed:", err);
    process.exit(1);
  }
}

seed();
